Repository opentracing/opentracing-csharp, pull requests merged in 2018-05, with the labels that each got.

#89 Add nuget package installation instructions
  README.md
Labels: enhancement

#82 Add AppVeyor CI configuration
  .appveyor.yml
Labels: enhancement

#75 StartActive() overload with finishSpanOnDispose:true
  src/OpenTracing/IScopeManager.cs
  src/OpenTracing/ISpan.cs
  src/OpenTracing/ISpanBuilder.cs
  src/OpenTracing/Mock/MockSpanBuilder.cs
  src/OpenTracing/Noop/NoopSpanBuilder.cs
Labels: breaks-tracers, deviation-from-java, enhancement

#72 Added SetTag and WithTag for use with OpenTracing.Tag.Tags
  src/OpenTracing/ISpan.cs
  src/OpenTracing/ISpanBuilder.cs
  src/OpenTracing/Mock/MockSpan.cs
  src/OpenTracing/Mock/MockSpanBuilder.cs
  src/OpenTracing/Noop/NoopSpan.cs
  src/OpenTracing/Noop/NoopSpanBuilder.cs
Labels: breaks-tracers, enhancement

#99 AsyncLocalScopeManager isolation
  src/OpenTracing/Util/AsyncLocalScopeManager.cs
  test/OpenTracing.Tests/Util/AsyncLocalScopeManagerTests.cs
Labels: bug

#91 Use IEnumerable<KeyValuePair<string, object>> for Log() methods (again)
  src/OpenTracing/ISpan.cs
  src/OpenTracing/Mock/MockSpan.cs
  src/OpenTracing/Noop/NoopSpan.cs
Labels: breaks-tracers, deviation-from-java, enhancement

#100 Calculate version number based on environment/github tag
  .appveyor.yml
  Directory.Build.props
  build.ps1
  version.props
Labels: infrastructure
