Repository opentracing/opentracing-csharp, pull requests merged in 2018-02, with the labels that each got.

#59 finishSpanOnDispose instead of finishSpanOnClose
  src/OpenTracing/IScopeManager.cs
  src/OpenTracing/ISpanBuilder.cs
Labels: deviation-from-java, enhancement

#57 NoopTracer ported from Java
  src/OpenTracing/Noop/NoopScopeManager.cs
  src/OpenTracing/Noop/NoopSpan.cs
  src/OpenTracing/Noop/NoopSpanBuilder.cs
  src/OpenTracing/Noop/NoopSpanContext.cs
  src/OpenTracing/Noop/NoopTracer.cs
  src/OpenTracing/Noop/NoopTracerFactory.cs
  src/OpenTracing/Properties/AssemblyInfo.cs
  test/OpenTracing.Tests/Noop/NoopTests.cs
Labels: enhancement

#63 AsyncLocal based scope manager (ported from Java)
  build-definition.ps1
  src/OpenTracing/OpenTracing.csproj
  src/OpenTracing/Util/AsyncLocalScope.cs
  src/OpenTracing/Util/AsyncLocalScopeManager.cs
  test/OpenTracing.Tests/OpenTracing.Tests.csproj
  test/OpenTracing.Tests/Util/AsyncLocalScopeManagerTests.cs
  test/OpenTracing.Tests/Util/AsyncLocalScopeTests.cs
Labels: enhancement

#61 GlobalTracer ported from Java
  src/OpenTracing/Util/GlobalTracer.cs
  test/OpenTracing.Tests/Util/GlobalTracerTestUtil.cs
  test/OpenTracing.Tests/Util/GlobalTracerTests.cs
Labels: enhancement

#64 Remove exception types `OpenTracingException` and `UnsupportedFormatException`
  src/OpenTracing/ITracer.cs
  src/OpenTracing/OpenTracingException.cs
  src/OpenTracing/UnsupportedFormatException.cs
Labels: breaking-change

#54 added MockTracer and MockTracer.Tests projects
  src/OpenTracing/Mock/MockSpan.cs
  src/OpenTracing/Mock/MockSpanBuilder.cs
  src/OpenTracing/Mock/MockSpanContext.cs
  src/OpenTracing/Mock/MockTracer.cs
  src/OpenTracing/Mock/Propagators.cs
  test/OpenTracing.Tests/Mock/MockSpanTests.cs
  test/OpenTracing.Tests/Mock/MockTracerTests.cs
Labels: enhancement
